// Package storage defines the core types of plainoldanalytics: the Capture
// produced for every served request, the stored records (Traffic, Event,
// ReplayChunk), the derived Session, the Storage interface that backends
// implement, and the shared Config built with NewConfig.
//
// A session is identified by a session-only browser cookie. A visitor is a
// separate long-lived browser identity, retained across browser sessions.
//
// IDs (traffic, events, visitors) are snowflake-style uint64s minted
// server-side by NewID; they are time-ordered and never generated by
// clients. On the wire (cookies, URLs, JSON) they travel in decimal string
// form because JavaScript numbers lose precision past 2^53.
package storage

import (
	"context"
	"crypto/rand"
	"encoding/binary"
	"errors"
	"net"
	"net/http"
	"net/netip"
	"strings"
	"sync"
	"time"
)

// ErrNotFound is returned by lookups for an unknown ID.
var ErrNotFound = errors.New("not found")

// Capture holds the data collected while serving a request.
type Capture struct {
	// Pattern is the matched route pattern in ServeMux form without the
	// method prefix (e.g. "/b/{c}"); the method lives on the request.
	Pattern    string
	Status     int
	Size       int
	Time       time.Time
	Duration   time.Duration
	PathValues map[string]string
	// Visitor is the long-lived tracking-cookie visitor ID, if visitor
	// tracking is on; 0 means no visitor.
	Visitor uint64
	// Session is the browser-session ID carried in the session-only cookie.
	Session uint64
	// Context holds request attributes attached with capture.Set (e.g. "user").
	Context map[string]string
}

// Traffic is a recorded request as returned by queries.
type Traffic struct {
	ID          uint64              `json:"id"`
	Method      string              `json:"method"`
	Pattern     string              `json:"pattern"`
	QueryParams map[string][]string `json:"query_params"`
	PathParams  map[string]string   `json:"path_params"`
	Headers     map[string][]string `json:"headers"`
	Status      int                 `json:"status"`
	Size        int                 `json:"size"`
	Time        time.Time           `json:"time"`
	Duration    time.Duration       `json:"duration"`
	IP          string              `json:"ip"`
	Visitor     uint64              `json:"visitor"`
	Session     uint64              `json:"session"`
	Context     map[string]string   `json:"context"`
}

// Event is a custom analytics event tracked from the frontend (or backend).
type Event struct {
	ID      uint64         `json:"id"`
	Time    time.Time      `json:"time"`
	Name    string         `json:"name"`
	Props   map[string]any `json:"props"`
	Visitor uint64         `json:"visitor"`
	Session uint64         `json:"session"`
	Path    string         `json:"path"`
	IP      string         `json:"ip"`
}

// ReplayChunk is a batch of rrweb events for one session recording.
type ReplayChunk struct {
	ID      uint64    `json:"id"`
	Time    time.Time `json:"time"`
	Visitor uint64    `json:"visitor"`
	Session uint64    `json:"session"`
	// Data is a JSON array of rrweb events.
	Data []byte `json:"data"`
}

// Session is one browser session. Its ID comes from a session-only cookie;
// it is addressed by (Visitor, Start) for dashboard URLs.
type Session struct {
	Visitor      uint64    `json:"visitor"`
	ID           uint64    `json:"id"`
	Start        time.Time `json:"start"`
	End          time.Time `json:"end"`
	TrafficCount int       `json:"traffic_count"`
	EventCount   int       `json:"event_count"`
	HasReplay    bool      `json:"has_replay"`
	// Annotation is the last non-empty context value for the filter's
	// AnnotateKey seen during the session (e.g. the user), if requested.
	Annotation string `json:"annotation,omitempty"`
}

// SeriesPoint is one bucket of a time series.
type SeriesPoint struct {
	Bucket time.Time `json:"bucket"`
	Count  int       `json:"count"`
}

// NameCount is one row of a breakdown: a value and how many requests
// carried it.
type NameCount struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}

// TrafficStats are the dashboard's aggregate statistics over a time window.
// The breakdowns are ordered by count descending. Referrers and UserAgents
// are raw header values; presentation-level grouping (referrer host,
// browser/OS/device) is the caller's job.
type TrafficStats struct {
	// Views is the number of requests in the window.
	Views int `json:"views"`
	// Visitors is the number of distinct (non-zero) visitors in the window.
	Visitors int `json:"visitors"`
	// Pages are the most requested route patterns.
	Pages []NameCount `json:"pages"`
	// Referrers are the most common raw Referer header values; requests
	// without one are not counted.
	Referrers []NameCount `json:"referrers"`
	// UserAgents are the most common raw User-Agent header values.
	UserAgents []NameCount `json:"user_agents"`
	// Users are the most common values of the requested context key;
	// empty when no key was given.
	Users []NameCount `json:"users"`
}

// TrafficFilter narrows Traffic queries; zero values mean "any".
type TrafficFilter struct {
	Pattern string // substring match
	Status  int
	Visitor uint64
	// From/To bound the traffic's timestamps when non-zero.
	From, To time.Time
	// ContextKey/ContextValue keep only traffic recorded with this context
	// pair (e.g. "user"="jay") — context keys are whatever the programmer
	// registered on the Capturer.
	ContextKey   string
	ContextValue string
}

// EventFilter narrows Events queries; zero values mean "any".
type EventFilter struct {
	Name    string
	Visitor uint64
	// From/To bound the events' timestamps when non-zero.
	From, To time.Time
}

// SessionFilter narrows Sessions queries; zero values mean "any".
type SessionFilter struct {
	Visitor uint64
	// AnnotateKey asks for each session's Annotation: the last non-empty
	// context value under this key (e.g. "user").
	AnnotateKey string
	// ContextKey/ContextValue keep only sessions whose traffic carried this
	// context pair (e.g. "user"="jay").
	ContextKey   string
	ContextValue string
	// EventName keeps only sessions in which this event occurred.
	EventName string
}

// Storage receives captured traffic, custom events, and replay data, and
// answers queries over what it has stored.
type Storage interface {
	Record(r *http.Request, c Capture)
	Traffic(ctx context.Context, f TrafficFilter) ([]Traffic, error)
	TrafficByID(ctx context.Context, id uint64) (Traffic, error)
	// TrafficSeries buckets request counts since the given time.
	TrafficSeries(ctx context.Context, since time.Time, bucketMinutes int) ([]SeriesPoint, error)
	// TrafficStats aggregates dashboard statistics over traffic since the
	// given time; userKey selects the context key for the Users breakdown
	// ("" skips it).
	TrafficStats(ctx context.Context, since time.Time, userKey string) (TrafficStats, error)
	TrackEvent(ctx context.Context, e Event) error
	Events(ctx context.Context, f EventFilter) ([]Event, error)
	SaveReplay(ctx context.Context, c ReplayChunk) error
	// Replay returns a visitor's replay chunks within [from, to] in
	// recording order (a derived session's window).
	Replay(ctx context.Context, visitor uint64, from, to time.Time) ([]ReplayChunk, error)
	Sessions(ctx context.Context, f SessionFilter) ([]Session, error)
}

// IdentityStore is optionally implemented by storage backends that can turn
// prior anonymous traffic from one persistent browser identity into a known
// user. Capturer uses it when a handler calls Set with Config.UserKey.
type IdentityStore interface {
	Identify(ctx context.Context, visitor uint64, userKey, user string) error
}

// idEpoch is the snowflake epoch: 2026-01-01 UTC in Unix milliseconds.
const idEpoch = 1767225600000

var (
	idMu   sync.Mutex
	idLast int64
	idSeq  uint64
	// idNode distinguishes processes writing to the same database; random
	// per process start.
	idNode = func() uint64 {
		var b [2]byte
		rand.Read(b[:])
		return uint64(binary.BigEndian.Uint16(b[:])) & 0x3FF
	}()
)

// NewID returns a time-ordered unique ID: a snowflake-style uint64 packing
// 41 bits of milliseconds since idEpoch, 10 bits of process node, and a
// 12-bit per-millisecond sequence.
func NewID() uint64 {
	idMu.Lock()
	defer idMu.Unlock()
	now := time.Now().UnixMilli()
	if now == idLast {
		idSeq++
		if idSeq > 0xFFF {
			for now <= idLast {
				now = time.Now().UnixMilli()
			}
			idSeq = 0
		}
	} else {
		idSeq = 0
	}
	idLast = now
	return uint64(now-idEpoch)<<22 | idNode<<12 | idSeq
}

// ClientIP returns the originating client address. Behind a proxy or load
// balancer, RemoteAddr is the proxy's address; the original client is the
// leftmost X-Forwarded-For entry (appended by each proxy in the chain), with
// X-Real-IP as a common single-value alternative. Candidates are validated
// as IPs so a malformed header falls through rather than polluting the data.
// Note that these headers are client-supplied: they are only trustworthy
// when a proxy you control strips or overwrites them.
func ClientIP(r *http.Request) string {
	if xff := r.Header.Get("X-Forwarded-For"); xff != "" {
		first, _, _ := strings.Cut(xff, ",")
		if ip, err := netip.ParseAddr(strings.TrimSpace(first)); err == nil {
			return ip.String()
		}
	}
	if xrip := strings.TrimSpace(r.Header.Get("X-Real-Ip")); xrip != "" {
		if ip, err := netip.ParseAddr(xrip); err == nil {
			return ip.String()
		}
	}
	ip := r.RemoteAddr
	if host, _, err := net.SplitHostPort(ip); err == nil {
		ip = host
	}
	return ip
}
